### ISSUE TITLE
[BUG] - Name of the Issue

### ISSUE THREAD

**Issue by bloodedge9** [OpenKH/OpenKh#1111]
OpenKH requires LuaBackend files for mods to work.
Kingdom Hearts 2 Final Mix quits unexpectedly due to the dll and tombl files.
The rest of the games in the compilation work correctly, except on KH2FM.

**Comment by shananas** [comment]
openkh does not require lua abckend for mods to work. it provides an easy way in the setup wizard to install it to work with panacea/mod loader since Lua Backend needs to be renamed/installed differently.
Mods that use lua files require lua backend to work and the lua files (mods) themselves need to update this is not an issue with openkh.
the only thing openkh has not been updated to do would be change the .toml depending on if you are installing for steam/EGS since their default scripts locations differ inside of the documents folder. This would just be a niceity if it gets added but as of now if a steam user has both EGS and steam version installed they can open the .toml in any text editor and update it so the filepath is correct depending on EGS/Steam (by defualt the TOML is configured for EGS so the user would need to comment out the first game_docs line by adding a `#` before it and uncomment out the steam line by removing the `#` before it

**Comment by bloodedge9** [comment]
OpenKh has created the files "DBGHELP.dll", "lua54.dll", "LuaBackend.dll", "LuaBackend.toml" and a text document "panacea_settings" after giving the installation command in the Mods Manager.
But as I said earlier, these files prevent loading a save game or starting a new one in Kingdom Hearts 2 Final Mix.
Deleting these files (except "panacea_settings") will not load the mods into "mod loader".
This happens from the game update to 1.0.0.10_WW. It only happens to me, the rest of the games like KH1, KHReCom and BBS work correctly.
________________________________
De: shananas ***@***.***>
Enviado: domingo, 8 de septiembre de 2024 23:57
Para: OpenKH/OpenKh ***@***.***>
Cc: joaquin ***@***.***>; Author ***@***.***>
Asunto: Re: [OpenKH/OpenKh] [BUG] - Name of the Issue (Issue #1111)


openkh does not require lua backend for mods to work. it provides an easy way in the setup wizard to install it to work with panacea/mod loader since Lua Backend needs to be renamed/installed differently.
Mods that use lua files require lua backend to work and the lua files (mods) themselves need to update this is not an issue with openkh.
the only thing openkh has not been updated to do would be change the .toml depending on if you are installing for steam/EGS since their default scripts locations differ inside of the documents folder. This would just be a niceity if it gets added but as of now if a steam user has both EGS and steam version installed they can open the .toml in any text editor and update it so the filepath is correct depending on EGS/Steam (by defualt the TOML is configured for EGS so the user would need to comment out the first game_docs line by adding a # before it and uncomment out the steam line by removing the # before it

**Comment by shananas** [comment]
when using openkh DBGHELP.dll is from openkh aswell as panacea_settings.txt if you are crashing with these in and not the other 3 mentioned files then you need to update your mod manager. Note if you use the mod manager the KH2Rando server they have not pulled the changes that fix this issue. If you wish to use mod manager with the newest game you mush get it from the latest release of this github repository.
if you have and are still crashing as i said this is a lua script issue. Not only are Lua Scripts not openkh's problem to fix they arent even Lua Backends problem to fix each mod author needs to fix and update their own lua scripts and then each user of those lua scripts needs to delete the old ones and get the new ones.
