### ISSUE TITLE
[BUG] - Can't Extract Game Data in the initial Setup of the Mod Manager

### ISSUE THREAD

**Issue by Frate27** [OpenKH/OpenKh#1127]
**OpenKH Build**
OpenKh Build 1259 (master) 
tried out other builds aswell

**OpenKH Program**
Mod Manager

**Describe the Bug**
In the initial setup, it askes me to extract the game data. When I click on the "Extract game data" button it gives me this error:
`An Exception was caught!
Value cannot be null. (Parameter path1")`

I was trying to extract KH3D (Dream Drop Distance), if that mathers.

**To Reproduce**
1. Open Mod Manager
2. Go trough the initial setup, until "Set Game Data Location"
3. Mark KH3D
4. Click on "Extract game Data"
5. See Error 

**Expected behavior**
It should just Extract the game data to the correct location

**Screenshots**
![Unbenannt](https://github.com/user-attachments/assets/813bae67-3f40-4f65-bd35-bf5670392748)

**Comment by shananas** [comment]
I think i know why open `mods-manager.yml` itll be in the folder next to the mod manager exe and remove `- kh2` before i added KH3D support i made the default always have KH2 and since you havent selected a path for that and cannot see the KH2 checkbox since you havent chosen the installation for it its trying to extract KH2 first then KH3D making a fix now but you can do this to extract now vs waiting for it to be merged.

**Comment by shananas** [comment]
fixed with #1128 but you will still want to delete the `mods-manager.yml` file after updating and restart mod manager and rerun the setup wizard
